#!/usr/bin/env bash

echo "Running spotless on library"
cd library
mvn spotless:apply

echo "Running spotless on cli"
cd ../cli
mvn spotless:apply

echo "Running spotless on backend"
cd ../backend
mvn spotless:apply

echo "Running prettier on frontend"
cd ../frontend
npm run format
